export const FETCH_API_RECIPES = 'fetch_api_recipes'
export const FETCH_SEARCH_RECIPES = 'fetch_search_recipes'
export const FETCH_ACCOUNT_RECIPES = 'fetch_account_recipes'
export const CREATE_USER = 'create_user'
export const LOGIN_USER = 'login_user'
export const LOGOUT_USER = 'logout_user'
export const ADD_SYS_RECIPE = 'add_sys_recipe'
export const ADD_USER_RECIPE = 'add_user_recipe'
export const EDIT_USER_RECIPE = 'edit_user_recipe'
export const DELETE_RECIPE = 'delete_recipe'

